# Generated by Django 2.1.7 on 2019-03-23 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190314_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited_users',
            field=models.ManyToManyField(null=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(null=True, related_name='registered_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
