# Generated by Django 2.1.7 on 2019-04-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190430_1330'),
        ('events', '0008_auto_20190430_0229'),
    ]

    operations = [
    ]
