# Generated by Django 2.1.7 on 2019-04-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190430_1342'),
        ('events', '0012_auto_20190430_2047'),
    ]

    operations = [
    ]
