# Generated by Django 2.1.7 on 2019-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
    ]
